package com.Polytech.rechargeBatterie;


import com.codename1.components.SpanLabel;
import com.codename1.components.ToastBar;
import static com.codename1.ui.CN.*;
import com.codename1.io.Log;
import java.io.IOException;
import com.codename1.ui.*;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.layouts.GridLayout;
import com.codename1.ui.table.TableLayout;
import java.util.ArrayList;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class LogIn extends Scene{
    
    private final TextField _username;
    private final TextField _password;
    private final Button _play_b;
    
    public LogIn(SceneManager sm) {
        super(sm);
        _sceneManager = sm;
        
        _form = new Form("Afortunadamente", BoxLayout.y());
        _form.add(new Label("Escribe el nombre de los participantes"));
        
        //Create the player fields
        _username = new TextField("","Username", 20, TextArea.ANY);
        _form.add(_username);
        _password = new TextField("","Password", 20, TextArea.ANY);
        _form.add(_password);
        _play_b = new Button("Jugar");
        _play_b.addActionListener((ActionEvent e) -> destroyScene());
        _form.add(_play_b);
    }
}
