package com.Polytech.rechargeBatterie;


import com.codename1.ui.*;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.layouts.GridLayout;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class LogIn extends Scene{
    
    private final TextField _username;
    private final TextField _password;
    //Contains the buttons
    private final Container _buttonLayout;
    private final Button _submit_b;
    private final Button _signIn_b;
    
    public LogIn(SceneManager sm) {
        super(sm);
        _sceneManager = sm;
        
        _form = new Form("Reprend de l'énergie", BoxLayout.y());
        _form.add(new Label("Inscription"));
        
        //Create the player fields
        _username = new TextField("","Username", 20, TextArea.ANY);
        _form.add(_username);
        _password = new TextField("","Password", 20, TextArea.ANY);
        _password.setConstraint(TextField.PASSWORD);
        _form.add(_password);
        
        //Horizontal button layout
        _buttonLayout = new Container (new GridLayout(1,2));
        _submit_b = new Button("Submit");
        _signIn_b = new Button("Sign In");
        //Create on click events
        _submit_b.addActionListener((ActionEvent e) -> destroyScene(1));
        _signIn_b.addActionListener((ActionEvent e) -> destroyScene(2));
        _buttonLayout.addAll(_submit_b, _signIn_b);
        _form.add(_buttonLayout);
    }
}
