package com.Polytech.rechargeBatterie;


import static com.codename1.ui.CN.*;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.Button;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form _current;
    private Resources _theme;
    private SceneManager _sceneManager;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        _theme = UIManager.initFirstTheme("/theme");
        _sceneManager = new SceneManager();

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });       
    }
    
    public void start() {
        if(_current != null){
            _current.show();
            return;
        }
        
        //to initialize google maps
        _sceneManager.setMap(1);
    }

    public void stop() {
        _current = getCurrentForm();
        if(_current instanceof Dialog) {
            ((Dialog)_current).dispose();
            _current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}
