package com.Polytech.rechargeBatterie;


import com.codename1.ui.*;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.layouts.GridLayout;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class SignIn extends Scene{
    
    private final TextField _username_tf;
    private final TextField _password_tf;
    private final TextField _confirmPassword_tf;
    private final TextField _address_tf;
    
    public SignIn(SceneManager sm) {
        super(sm);
        _sceneManager = sm;
        
        _form = new Form("Reprend de l'énergie", BoxLayout.y());
        _form.add(new Label("Inscription"));
        
        //Create the player fields
        _username_tf = new TextField("","Username", 20, TextArea.ANY);
        _form.add(_username_tf);
        //passwords
        _password_tf = new TextField("","Password", 20, TextArea.ANY);
        _password_tf.setConstraint(TextField.PASSWORD);
        _form.add(_password_tf);
        _confirmPassword_tf = new TextField("","Password", 20, TextArea.ANY);
        _confirmPassword_tf.setConstraint(TextField.PASSWORD);
        _form.add(_confirmPassword_tf);
        //adress
        _address_tf = new TextField("","Address", 20, TextArea.ANY);
        _address_tf.setConstraint(TextField.PASSWORD);
        _form.add(_address_tf);
    }
}
